### PR TITLE
Enable camera in boot parameters

### PR DESCRIPTION
**Pull request by icarito**
Also test CI build

### CODE REVIEW

**Comment by icarito** [comment]
Test image built automatically!
https://gitlab.com/publiclab/image-builder-rpi/-/jobs/86241409/artifacts/browse

**Comment by icarito** [comment]
I just tested the build artifact image built at Gitlab CI! It works well, and this patch enabled `raspistill` to work without reconfiguration. Merging!

**Comment by icarito** [comment]
I tested it with `raspistill` - no web interface yet. This was more of a test of auto-building for every merge request! But next steps should be not-so-difficult, see https://gitlab.com/publiclab/image-builder-rpi/issues/9.

**Comment by jywarren** [comment]
OK cool, and just a single, or multiple shots? I can plug in a camera and test if you like or hold off for a bit?

**Comment by icarito** [comment]
I tried a couple of shots.

**Pull request merged**
